export const nativeAmountFields = [
  ["Balances", "force_set_balance", "new_free"],
  ["Balances", "force_transfer", "value"],
  ["Balances", "force_unreserved", "amount"],
  ["Balances", "transfer_allow_death", "value"],
  ["Balances", "transfer_keep_alive", "value"],
  ["Staking", "bond", "value"],
  ["Staking", "bond_extra", "max_additional"],
  ["Staking", "rebond", "value"],
  ["Staking", "unbond", "value"],
  ["NominationPools", "bond_extra", "extra", "FreeBalance"],
  ["NominationPools", "create", "amount"],
  ["NominationPools", "create_with_pool_id", "amount"],
  ["NominationPools", "join", "amount"],
  ["NominationPools", "unbond", "unbonding_points"],
  ["ConvictionVoting", "delegate", "balance"],
  ["ConvictionVoting", "vote", "vote", "Split", "aye"],
  ["ConvictionVoting", "vote", "vote", "Split", "nay"],
  ["ConvictionVoting", "vote", "vote", "SplitAbstain", "aye"],
  ["ConvictionVoting", "vote", "vote", "SplitAbstain", "nay"],
  ["ConvictionVoting", "vote", "vote", "SplitAbstain", "abstain"],
  ["ConvictionVoting", "vote", "vote", "Standard", "balance"],
  ["Treasury", "spend_local", "amount"],
  ["Bounties", "propose_bounty", "value"],
  ["Bounties", "propose_curator", "fee"],
  ["ChildBounties", "add_child_bounty", "value"],
  ["ChildBounties", "propose_curator", "fee"],
] as const;
